/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TecnologiaRouteImport } from './routes/tecnologia'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as EngenhariaDePresencaRouteImport } from './routes/engenharia-de-presenca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperienciasMarcasRouteImport } from './routes/experiencias.marcas'
import { Route as ExperienciasEventosRouteImport } from './routes/experiencias.eventos'
import { Route as ExperienciasCulturaRouteImport } from './routes/experiencias.cultura'

const TecnologiaRoute = TecnologiaRouteImport.update({
  id: '/tecnologia',
  path: '/tecnologia',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const EngenhariaDePresencaRoute = EngenhariaDePresencaRouteImport.update({
  id: '/engenharia-de-presenca',
  path: '/engenharia-de-presenca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasMarcasRoute = ExperienciasMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => ExperienciasRoute,
} as any)
const ExperienciasEventosRoute = ExperienciasEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => ExperienciasRoute,
} as any)
const ExperienciasCulturaRoute = ExperienciasCulturaRouteImport.update({
  id: '/cultura',
  path: '/cultura',
  getParentRoute: () => ExperienciasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/engenharia-de-presenca': typeof EngenhariaDePresencaRoute
  '/experiencias': typeof ExperienciasRouteWithChildren
  '/parceiros': typeof ParceirosRoute
  '/tecnologia': typeof TecnologiaRoute
  '/experiencias/cultura': typeof ExperienciasCulturaRoute
  '/experiencias/eventos': typeof ExperienciasEventosRoute
  '/experiencias/marcas': typeof ExperienciasMarcasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/engenharia-de-presenca': typeof EngenhariaDePresencaRoute
  '/experiencias': typeof ExperienciasRouteWithChildren
  '/parceiros': typeof ParceirosRoute
  '/tecnologia': typeof TecnologiaRoute
  '/experiencias/cultura': typeof ExperienciasCulturaRoute
  '/experiencias/eventos': typeof ExperienciasEventosRoute
  '/experiencias/marcas': typeof ExperienciasMarcasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/engenharia-de-presenca': typeof EngenhariaDePresencaRoute
  '/experiencias': typeof ExperienciasRouteWithChildren
  '/parceiros': typeof ParceirosRoute
  '/tecnologia': typeof TecnologiaRoute
  '/experiencias/cultura': typeof ExperienciasCulturaRoute
  '/experiencias/eventos': typeof ExperienciasEventosRoute
  '/experiencias/marcas': typeof ExperienciasMarcasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/engenharia-de-presenca'
    | '/experiencias'
    | '/parceiros'
    | '/tecnologia'
    | '/experiencias/cultura'
    | '/experiencias/eventos'
    | '/experiencias/marcas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/engenharia-de-presenca'
    | '/experiencias'
    | '/parceiros'
    | '/tecnologia'
    | '/experiencias/cultura'
    | '/experiencias/eventos'
    | '/experiencias/marcas'
  id:
    | '__root__'
    | '/'
    | '/engenharia-de-presenca'
    | '/experiencias'
    | '/parceiros'
    | '/tecnologia'
    | '/experiencias/cultura'
    | '/experiencias/eventos'
    | '/experiencias/marcas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EngenhariaDePresencaRoute: typeof EngenhariaDePresencaRoute
  ExperienciasRoute: typeof ExperienciasRouteWithChildren
  ParceirosRoute: typeof ParceirosRoute
  TecnologiaRoute: typeof TecnologiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tecnologia': {
      id: '/tecnologia'
      path: '/tecnologia'
      fullPath: '/tecnologia'
      preLoaderRoute: typeof TecnologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias': {
      id: '/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof ExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engenharia-de-presenca': {
      id: '/engenharia-de-presenca'
      path: '/engenharia-de-presenca'
      fullPath: '/engenharia-de-presenca'
      preLoaderRoute: typeof EngenhariaDePresencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias/marcas': {
      id: '/experiencias/marcas'
      path: '/marcas'
      fullPath: '/experiencias/marcas'
      preLoaderRoute: typeof ExperienciasMarcasRouteImport
      parentRoute: typeof ExperienciasRoute
    }
    '/experiencias/eventos': {
      id: '/experiencias/eventos'
      path: '/eventos'
      fullPath: '/experiencias/eventos'
      preLoaderRoute: typeof ExperienciasEventosRouteImport
      parentRoute: typeof ExperienciasRoute
    }
    '/experiencias/cultura': {
      id: '/experiencias/cultura'
      path: '/cultura'
      fullPath: '/experiencias/cultura'
      preLoaderRoute: typeof ExperienciasCulturaRouteImport
      parentRoute: typeof ExperienciasRoute
    }
  }
}

interface ExperienciasRouteChildren {
  ExperienciasCulturaRoute: typeof ExperienciasCulturaRoute
  ExperienciasEventosRoute: typeof ExperienciasEventosRoute
  ExperienciasMarcasRoute: typeof ExperienciasMarcasRoute
}

const ExperienciasRouteChildren: ExperienciasRouteChildren = {
  ExperienciasCulturaRoute: ExperienciasCulturaRoute,
  ExperienciasEventosRoute: ExperienciasEventosRoute,
  ExperienciasMarcasRoute: ExperienciasMarcasRoute,
}

const ExperienciasRouteWithChildren = ExperienciasRoute._addFileChildren(
  ExperienciasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EngenhariaDePresencaRoute: EngenhariaDePresencaRoute,
  ExperienciasRoute: ExperienciasRouteWithChildren,
  ParceirosRoute: ParceirosRoute,
  TecnologiaRoute: TecnologiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
